[build]
command = "npm run build"
publish = "dist"

[dev]
command = "npm run dev"
port = 8888
targetPort = 3000
framework = "vite"

[build.environment]
NODE_VERSION = "22"
NPM_VERSION = "11"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200