[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# Configuration du scan des secrets
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_TEMPLATE_ID"